---
# tasks file for test-role-1
 - name: Ensure Apache2 is at the latest version
   apt:
     name: apache2
     state: latest
     update_cache: true
   notify:
    - Restart Apache     
 - name: Ensure Apache is running
   service:
     name: apache2
     state: started
